### ISSUE TITLE
sshkeys join("\n") concatenating with literal \n rather than newline

### ISSUE THREAD

**Issue by scosist** [debops/ansible-sshkeys#4]
With the following `sshkeys_list`:
```
        sshkeys_list: {
          name: root,
          sshkeys: [
            '{{ lookup("file", "~/id_rsa1.pub") }}',
            '{{ lookup("file", "~/id_rsa2.pub") }}'
          ]
```
The line in [question ](/debops/ansible-sshkeys/blob/master/tasks/main.yml#L18)
```
    key: '{{ item.sshkeys | unique | join("\n") | string }}'
```
is placing a literal `\n` in the target file rather than the expected newline.

Not sure why or what the cause of it is, but swapping the quotes gave the expected behavior, placing a newline between ssh keys.
```
    key: "{{ item.sshkeys | unique | join('\n') | string }}"
```

Would this be a recommended fix or would considering a different structure for `sshkeys` or something else be more desirable here?

Using https://github.com/debops/ansible-sshkeys/archive/master.tar.gz and Ansible 2.1.0.0

**Comment by drybjed** [comment]
No, using a list as it's currently done sounds fine to me. Execellent that swapping quotes fixed this, I'll update the role right away. Thanks!

**Comment by scosist** [comment]
Thanks for the quick fix.

This worked before when I was running Ansible 1.9.4 and an older version of sshkeys (although the line of code in question has always been the same). Any ideas what changed? Seems swapping quotes here should be unnecessary.

**Comment by scosist** [comment]
I haven't found anything that directly addresses this and it's a bit odd that it worked before. And although the [Porting Guide](https://docs.ansible.com/ansible/porting_guide_2.0.html) for Ansible 2.0 doesn't discuss rules for nesting quotes, all of their examples that involve single and double quotes show single quotes inside of double quotes.

**Comment by drybjed** [comment]
There were some changes related to how Ansible interpretes backslashes in task parameters, perhaps this is the same thing.

I'm using the `' "" '` order out of habit, but I don't have any preference here. Besides, quoting depends on the context:
```
var: "There's a snake in my boot!"
var: 'command="ls -l" ssh-rsa AAAAAAAA...'
```
Anywy, thanks for the fix. I'm working on updated role that will replace `debops.sshkeys` preserving backwards compatibility, should be out in a few hours.

**Comment by drybjed** [comment]
@scosist If you're interested, new [debops.authorized_keys](https://github.com/debops/ansible-authorized_keys/) role is up.
